// demos/react/src/components/Column/BoardColumn.tsx
import React from 'react';
import { useBoardColumn, useBoardState, DropIndicator } from '@agallaoui/board-dnd/react';
import type { Column, Task } from '../../types';
import { TicketCard } from '../Ticket';

interface BoardColumnProps {
  column: Column;
}

/**
 * Board column component with drop zone functionality
 * Handles drop indicator positioning for both cross-column and same-column drags
 */
export function BoardColumn({ column }: BoardColumnProps) {
  const { ref, itemsContainerRef, isOver, dropIndicator } = useBoardColumn({
    id: column.id,
    data: { title: column.title },
  });
  const boardState = useBoardState<Task>();

  // Check if we're dragging within the same column
  const isDraggingFromThisColumn = boardState.sourceColumnId === column.id;
  const draggedItemId = boardState.draggedItem?.id;

  // Calculate the actual insert index for UI rendering
  // When dragging within the same column, the engine calculates positions
  // excluding the dragged item, so we need to adjust for display
  const getAdjustedInsertIndex = (insertIndex: number): number => {
    if (!isDraggingFromThisColumn || !dropIndicator) return insertIndex;

    // Find the original index of the dragged item
    const draggedOriginalIndex = column.items.findIndex(
      (item) => item.id === draggedItemId
    );

    // Adjust the insert index to account for the dragged item still being in the list
    if (draggedOriginalIndex !== -1 && insertIndex > draggedOriginalIndex) {
      return insertIndex + 1;
    }
    return insertIndex;
  };

  const adjustedInsertIndex = dropIndicator
    ? getAdjustedInsertIndex(dropIndicator.insertIndex)
    : null;

  return (
    <div ref={ref} className={`column ${isOver ? 'over' : ''}`}>
      <div className="column-header">
        <h2>{column.title}</h2>
        <span className="item-count">{column.items.length}</span>
      </div>
      <div ref={itemsContainerRef} className="column-items">
        {column.items.map((task, index) => {
          // Don't show indicator at the dragged item's original position
          const showIndicator =
            adjustedInsertIndex === index && task.id !== draggedItemId;

          return (
            <React.Fragment key={task.id}>
              {showIndicator && <DropIndicator className="drop-indicator" />}
              <TicketCard task={task} columnId={column.id} index={index} />
            </React.Fragment>
          );
        })}
        {adjustedInsertIndex === column.items.length && (
          <DropIndicator className="drop-indicator" />
        )}
      </div>
    </div>
  );
}

// demos/angular/src/app/components/column/board-column.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { Column, Task } from '../../types';
import { BoardDndService } from '../../services';
import { BoardColumnDirective, BoardItemDirective } from '../../directives';
import { TicketCardComponent } from '../ticket';

/**
 * Board column component with drop zone functionality
 * Handles drop indicator positioning for both cross-column and same-column drags
 */
@Component({
  selector: 'app-board-column',
  standalone: true,
  imports: [
    CommonModule,
    BoardColumnDirective,
    BoardItemDirective,
    TicketCardComponent,
  ],
  templateUrl: './board-column.component.html',
  styleUrl: './board-column.component.scss',
})
export class BoardColumnComponent {
  @Input({ required: true }) column!: Column;

  constructor(private boardService: BoardDndService) {}

  /**
   * Check if we should show the drop indicator at a given index
   */
  shouldShowIndicatorAt(index: number, taskId: string): boolean {
    const adjustedIndex = this.getAdjustedInsertIndex();
    if (adjustedIndex === null) return false;

    // Don't show indicator at the dragged item's position
    const draggedItemId = this.boardService.state.draggedItem?.id;
    if (taskId === draggedItemId) return false;

    return adjustedIndex === index;
  }

  /**
   * Get the adjusted insert index for UI rendering
   * When dragging within the same column, the engine calculates positions
   * excluding the dragged item, so we need to adjust for display
   */
  getAdjustedInsertIndex(): number | null {
    const indicator = this.boardService.getDropIndicatorForColumn(this.column.id);
    if (!indicator) return null;

    const isDraggingFromThisColumn =
      this.boardService.state.sourceColumnId === this.column.id;

    if (!isDraggingFromThisColumn) {
      return indicator.insertIndex;
    }

    // Find the original index of the dragged item
    const draggedItemId = this.boardService.state.draggedItem?.id;
    const draggedOriginalIndex = this.column.items.findIndex(
      (item: Task) => item.id === draggedItemId
    );

    // Adjust the insert index to account for the dragged item still being in the list
    if (draggedOriginalIndex !== -1 && indicator.insertIndex > draggedOriginalIndex) {
      return indicator.insertIndex + 1;
    }

    return indicator.insertIndex;
  }
}

<div
  class="column"
  boardColumn
  [boardColumnId]="column.id"
  [boardColumnData]="column"
>
  <div class="column-header">
    <h2>{{ column.title }}</h2>
    <span class="item-count">{{ column.items.length }}</span>
  </div>

  <div class="column-items">
    <ng-container *ngFor="let task of column.items; let i = index">
      <!-- Drop indicator before item (not at dragged item's position) -->
      <div
        *ngIf="shouldShowIndicatorAt(i, task.id)"
        class="drop-indicator"
      ></div>

      <!-- Task card -->
      <div
        class="task-card"
        boardItem
        [boardItemId]="task.id"
        [boardItemData]="task"
        [boardItemColumnId]="column.id"
        [boardItemIndex]="i"
      >
        <app-ticket-card [task]="task" />
      </div>
    </ng-container>

    <!-- Drop indicator at end -->
    <div
      *ngIf="getAdjustedInsertIndex() === column.items.length"
      class="drop-indicator"
    ></div>
  </div>
</div>
